version: '2'

services:
    php:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: php
        image: web-crawler-alpha
        environment:
            PHP_IDE_CONFIG: "serverName=web-crawler-alpha.php"
        volumes:
            - ./:/var/www/html:delegated
